project:
  type: website

website:
  title: "Clinica de olhos Aderbal Alves"
  site-url: https://clinicadeolhos.netlify.app
  description: O site do Aderbal
  image: aderbal_chico.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - team.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

