---
title: "Exames e Procedimentos"
---

O exame oftalmológico é uma avaliação dos olhos, pálpebras e vias lacrimais que tem particular importância em determinadas etapas da vida. Nos bebês deve-se verificar o clarão pupilar para identificar precocemente algum problema de visão. Já as crianças precisam fazer exames oftalmológicos com regularidade para detectar eventuais deficiências, que podem prejudicar o aprendizado escolar.

Outra etapa em que o exame se torna inevitável ocorre em torno dos 40 anos de idade. Com a passagem do tempo, percebemos falhas na visão para perto e os textos com letras pequenas ficam difíceis de serem lidos. São os sintomas da vista cansada (ou presbiopia), que pode ser corrigida com as modernas lentes multifocais, que oferecem características adequadas a cada situação, contribuindo para o aumento do conforto visual.

O exame oftalmológico de rotina deve abranger diversos itens. Em primeiro lugar, uma avaliação externa para verificação da normalidade das pálpebras e do segmento anterior do olho. Depois, o teste da refração – optometria - que dará o grau do paciente, permitindo verificar a gravidade da deficiência. Já o exame do fundo de olho serve para uma análise sumária da retina e do nervo óptico, encontrando alterações relacionadas com outras doenças, tais como diabetes, hipertensão arterial.

Outro item imprescindível no exame oftalmológico é a tonometria (medida de pressão ocular). Hoje está provado que o maior fator de risco no desenvolvimento do glaucoma é a pressão ocular elevada, principalmente em pacientes que tenham antecedentes familiares da doença. O glaucoma atinge cerca de 2% da população, e por não ter manifestações aparentes, pode levar à cegueira, caso não seja tratada.

O exame oftalmológico, por suas ligações com a clínica médica, a neurologia e outras especialidades, é um elemento importante para o diagnóstico e acompanhamento de diversas doenças.

\[slideshow id=1\]

-   Retinografia
-   Angiografia fluoresceinica
-   Auto-fluorescência (sem contraste)
-   Yag laser(capsulotomia/iridectomia)
-   Fotocoagulação de Retina
-   Adaptação de lentes de contato - especiais(ceratocone/escleral/multifocais, etc)
-   Topografia da córnea
-   Microscopia especular da córnea
-   Paquimetria
-   EcoBiometria (tecnica de imersão)
-   Mapeamento de Retina
-   Acuidade Visual Potencial à laser (PAM)
-   Visão Subnormal
-   Senso Cromático
-   Tonometria
-   Gonioscopia
-   Campo Visual Computadorizado
-   Botox
-   Teste Shirmer e Rosa Bengala
